@baseUrl = http://localhost:3000/artists
@contentType = application/json

# make sure there is no empty space
@id = 1746545286618

### GET / - Get all artists
GET {{baseUrl}}/ HTTP/1.1
Accept: {{contentType}}

### GET /:id - Get artist by ID
GET {{baseUrl}}/{{id}} HTTP/1.1
Accept: {{contentType}}

### POST / - Create new artist
POST {{baseUrl}}/ HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Drake"
}

### PATCH /:id - Update artist
PATCH {{baseUrl}}/{{id}} HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Marshall Bruce Mathers III"
}

### DELETE /:id - Delete artist
DELETE {{baseUrl}}/{{id}} HTTP/1.1
