@baseUrl = http://localhost:8080/artists
@contentType = application/json

# make sure there is no empty space
@id = 1746547893740

### Get all artists
GET {{baseUrl}}/ HTTP/1.1
Accept: {{contentType}}

### Get artist by ID
GET {{baseUrl}}/{{id}} HTTP/1.1
Accept: {{contentType}}

//:TODO update to artists
### Search artists
POST {{baseUrl}}/search HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Drake"
}

### Create new artist
POST {{baseUrl}}/ HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Drake"
}

### Update artist
PATCH {{baseUrl}}/{{id}} HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Marshall Bruce Mathers III"
}

### Delete artist
DELETE {{baseUrl}}/{{id}} HTTP/1.1
