import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

export function runExportSchema(cwd: string, collectionName: string) {
    console.log(`\n📦 JSON Express — Schema Exporter\n`);
    
    if (!collectionName) {
        console.error('❌ Please provide a collection name. Example: json-express export albums');
        process.exit(1);
    }
    
    // 1. Find Data Source
    let dataPath = join(cwd, 'data', `${collectionName}.json`);
    if (!existsSync(dataPath)) {
        dataPath = join(cwd, `${collectionName}.json`);
        if (!existsSync(dataPath)) {
            console.error(`❌ Could not find ${collectionName}.json in /data or root directory.`);
            process.exit(1);
        }
    }
    
    // 2. Read and Infer
    const content = readFileSync(dataPath, 'utf8');
    const parsed = JSON.parse(content);
    const dataArray = Array.isArray(parsed) ? parsed : [parsed];
    const firstRecord = dataArray[0] || {};
    
    // 3. Generate TS Content
    const fieldsGen = Object.keys(firstRecord).map(key => {
        if (key === 'id') return `        id: types.id(),`;
        const val = firstRecord[key];
        if (typeof val === 'number') return `        ${key}: types.number(),`;
        if (typeof val === 'boolean') return `        ${key}: types.boolean(),`;
        // Basic date string detection
        if (typeof val === 'string' && !isNaN(Date.parse(val)) && val.includes('-')) {
             return `        ${key}: types.date(),`;
        }
        return `        ${key}: types.string(), // Detected from typeof: ${typeof val}`;
    }).join('\n');
    
    const tsContent = `import { defineModel, types } from '@json-express/core';

/**
 * Autogenerated Schema for '${collectionName}'
 * You can now modify this file to add relations, constraints, and custom endpoints.
 */
export default defineModel({
    fields: {
${fieldsGen || '        // add custom fields here\n        id: types.id()'}
    },
    endpoints: {
        // "GET /stats": async (req, res, ctx) => { res.send({ total: await ctx.db.count('${collectionName}') }) }
    },
    hooks: {
        // beforeCreate: async (data) => { return data; }
    }
});
`;

    // 4. Write to /models
    const modelsDir = join(cwd, 'models');
    if (!existsSync(modelsDir)) {
        mkdirSync(modelsDir);
    }
    
    const outPath = join(modelsDir, `${collectionName}.ts`);
    if (existsSync(outPath)) {
        console.error(`❌ Error: ${outPath} already exists! Cannot overwrite.`);
        process.exit(1);
    }
    
    writeFileSync(outPath, tsContent, 'utf8');
    console.log(`✅ Success! Exported ${collectionName}.json to strongly-typed TypeScript.`);
    console.log(`📂 Created: ./models/${collectionName}.ts`);
    
    // If it was in the root, tell them they can move it to /data
    if (dataPath === join(cwd, `${collectionName}.json`)) {
        console.log(`\n💡 Tip: You should move ./${collectionName}.json into a ./data/ folder to keep your root directory clean!`);
    }
}
